services:
  # Python Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    volumes:
      - ./AppDbStore:/app/AppDbStore
      - ./custom_kg:/app/custom_kg
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  # React Frontend
  frontend:
    build: 
      context: ./threadHunterUI
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  # Optional: Ollama service for LLM
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    profiles:
      - llm

volumes:
  ollama_data:
